# Generated by Django 5.1.6 on 2025-02-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgid', models.CharField(help_text='Original text (English)', max_length=255, unique=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], help_text='Language code', max_length=10)),
                ('msgstr', models.TextField(help_text='Translated text')),
            ],
            options={
                'unique_together': {('msgid', 'language')},
            },
        ),
    ]
