# Generated by Django 5.1.6 on 2025-02-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_translationentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationentry',
            name='msgid',
            field=models.CharField(help_text='Original text (English)', max_length=255),
        ),
    ]
