name: Django CI

on:
  push:
    branches:
      - main
      - feature/localization
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install django djangorestframework django-debug-toolbar

      - name: Run Migrations
        run: |
          source venv/bin/activate
          python manage.py migrate
      - name: Collect Static Files
        run: |
          source venv/bin/activate
          python manage.py collectstatic --noinput    

      - name: Run Tests
        run: |
          source venv/bin/activate
          python manage.py test
